#!/bin/sh
set -e
# Automatically added by dh_installudev
if [ "$1" = configure ]; then
	if [ -e "/etc/udev/rules.d/z60_openocd.rules" ]; then
		echo "Preserving user changes to /etc/udev/rules.d/60-openocd.rules ..."
		if [ -e "/etc/udev/rules.d/60-openocd.rules" ]; then
			mv -f "/etc/udev/rules.d/60-openocd.rules" "/etc/udev/rules.d/60-openocd.rules.dpkg-new"
		fi
		mv -f "/etc/udev/rules.d/z60_openocd.rules" "/etc/udev/rules.d/60-openocd.rules"
	fi
fi
# End automatically added section
